language: python
python:
  - 2.7
install: python setup.py install
script:  python setup.py test
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#clusto"
    on_success: change
    on_failure: always
